sudo: required
dist: trusty

branches:
  only:
    - master

compiler:
    - gcc

os:
    - linux

language: c

env:
    global:
        - PATH="$HOME/prefix/bin:$PATH"

addons:
    apt:
        sources:
            - llvm-toolchain-precise-3.8
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - check
            - clang-3.8
            - gcc-5
            - libblkid-dev
            - lcov
            - llvm-3.8
            - valgrind
            - gnu-efi
            - libefivar-dev
            - python3-pip


before_install:
  - gem install coveralls-lcov
  - mkdir -p $HOME/prefix/bin
  - pip3 install --user meson==0.44.1
  - wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
  - unzip ninja-linux.zip
  - mv ninja $HOME/prefix/bin/

script:
    - lcov --version | grep "1.10"
    - export CC="gcc-5"
    - ./scripts/travis_test.sh

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - coveralls-lcov outCoverage/coverage.info
