name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Prepare
      run: |
        sudo apt-get update
        sudo apt-get install libefiboot-dev check grep ninja-build meson gcc-5 libblkid-dev lcov valgrind gnu-efi libefivar-dev ruby ruby-dev rubygems
        sudo gem install coveralls-lcov
    - name: "Run Test: stock"
      env:
        CC: "gcc-5"
      run: |
        ./scripts/run-test-suite.sh stock && coveralls-lcov outCoverage/coverage.info
    - name: "Run Test: systemd"
      env:
        CC: "gcc-5"
      run: |
        ./scripts/run-test-suite.sh systemd && coveralls-lcov outCoverage/coverage.info
    - name: "Run Test: shim-systemd-boot"
      env:
        CC: "gcc-5"
      run: |
        ./scripts/run-test-suite.sh shim-systemd-boot && coveralls-lcov outCoverage/coverage.info
